### ISSUE TITLE
How to set the voxel_size and max_depth value for our own stereo dataset?

### ISSUE THREAD

**Issue by wgh-2018** [RIVeR-Lab/stereovoxelnet#1]
Hello, i want to test our own stereo dataset by visualize_hie.py
how to set the voxel_size and max_depth according to the camera intrinsics
thank you

**Comment by lhy0807** [comment]
Two lines control the max depth.
In the voxel cost volume formulation
https://github.com/RIVeR-Lab/stereovoxelnet/blob/08464b2e6384293d00d153deb84a6de16d3d5623/scripts/net/visualization/visualize_hie.py#L152
and in the dataset construction, like this (where the voxel size is defined)
https://github.com/RIVeR-Lab/stereovoxelnet/blob/08464b2e6384293d00d153deb84a6de16d3d5623/datasets/parse_rosbag.py#L55
If you plan to test on your own stereo dataset, I recommend fine-tuning the pretrained model using your own dataset.

**Comment by wgh-2018** [comment]
thanks for your reply! 
if i fine-tuning the pretrained model using my dataset， can i use the same max_depth and voxel_size as the DSdataset  when load my dataset？my camera Intrinsics and baseline is different from DSdataset.

**Comment by lhy0807** [comment]
Sure, you can use the same max_depth and voxel_size to train on your dataset. Let me know if you have more questions
