### ISSUE TITLE
No such file or directory: 'mat44.npy'

### ISSUE THREAD

**Issue by cvolkc** [RIVeR-Lab/stereovoxelnet#10]
[Thank you for the dataset provided through Gdrive](https://github.com/RIVeR-Lab/stereovoxelnet/issues/9)

When running `parse_rosbags.py`, it cannot find an apparent `mat44.npy` file.

```
  File "parse_rosbag.py", line 163, in <module>
    bag = Bag()
  File "parse_rosbag.py", line 150, in __init__
    self.mat44 = np.load("mat44.npy")
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'mat44.npy'
```
I then set the initialization to `self.mat44 = None` to catch the following code snippet:

```
99        if self.mat44 is None:
100            self.mat44 = self.listener.asMatrix("zed_left", data.header)
```

which however results in:
```
  File "parse_rosbag.py", line 171, in <module>
    bag.listen_pc(msg)
  File "parse_rosbag.py", line 100, in listen_pc
    self.mat44 = self.listener.asMatrix("zed_left", data.header)
AttributeError: 'Bag' object has no attribute 'listener'
```

Where could I get the mat44.npy file from? Thanks a lot! :)

**Comment by lhy0807** [comment]
Sorry for the missing file. I've uploaded it to the repo. Hope it works :)
https://github.com/RIVeR-Lab/stereovoxelnet/blob/main/datasets/mat44.npy
