### ISSUE TITLE
No module named 'utils.KittiColormap'

### ISSUE THREAD

**Issue by If-only1** [RIVeR-Lab/stereovoxelnet#2]
hi, I try to run  "visualize_compare.py",  but No module named 'utils.KittiColormap'.

**Comment by lhy0807** [comment]
I'm sorry my code cleanup caused some issues. Could you try to pull the new commit or delete that line?

**Comment by If-only1** [comment]
> I'm sorry my code cleanup caused some issues. Could you try to pull the new commit or delete that line?

Got it, thank you very much for your prompt answer.
