### ISSUE TITLE
Is cuda 11.3 OK？

### ISSUE THREAD

**Issue by Jessy-Huang** [RIVeR-Lab/stereovoxelnet#3]
My system is installed with cuda 11.3， is it OK？

**Comment by lhy0807** [comment]
I guess so, if you installed CUDA11.3-compatible torch etc.

**Comment by Jessy-Huang** [comment]
thanks，I am ytrying to run IT



---- Replied Message ----
| From | Hongyu ***@***.***> |
| Date | 03/03/2023 00:33 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [RIVeR-Lab/stereovoxelnet] Is cuda 11.3 OK？ (Issue #3) |

I guess so, if you installed CUDA11.3-compatible torch etc.
