### ISSUE TITLE
ModuleNotFoundError: No module named 'models.lacGwcNet'

### ISSUE THREAD

**Issue by ynjiun** [RIVeR-Lab/stereovoxelnet#5]
Hi 

When I tried to run 
`python visualize_compare.py`

I encountered the following error message:
```
Visualizing Lac
Traceback (most recent call last):
  File "visualize_compare.py", line 466, in <module>
    lac()    
  File "visualize_compare.py", line 366, in lac
    from models.lacGwcNet.networks.stackhourglass import PSMNet
ModuleNotFoundError: No module named 'models.lacGwcNet'
```

What am I missing? Please advise. Thanks a lot.

**Comment by lhy0807** [comment]
Hi,I was using the original code from the lacGwcNet repo for comparison. Maybe it's not a good idea for me to put their code here. If you also want to compare, feel free to clone their repo and download their checkpoint and fine-tune the DrivingStereo dataset.
