### ISSUE TITLE
function “project_image_to_rect” issue？

### ISSUE THREAD

**Issue by wqx854987945** [RIVeR-Lab/stereovoxelnet#7]
Hi, in <dataset.py>  ,
`def project_image_to_rect(self, uv_depth):
        ''' Input: nx3 first two channels are uv, 3rd channel
                is depth in rect camera coord.
            Output: nx3 points in rect camera coord.
        '''
        n = uv_depth.shape[0]
        x = ((uv_depth[:, 0] - self.c_u) * uv_depth[:, 2]) / \
            self.f_u + self.baseline
        y = ((uv_depth[:, 1] - self.c_v) * uv_depth[:, 2]) / self.f_v`    
why should we add    "self.baseline"  ?  I think  left disparity  dont need this  operation？

**Comment by lhy0807** [comment]
Thanks for bringing this question up. This is to transform the point cloud from the left camera to the right camera in the stereo setup. I took this code snippet from the PseudoLidar paper
https://github.com/mileyan/pseudo_lidar/blob/032c7a0d73c3fdf84e934af3f57f8eb489a52906/preprocessing/kitti_util.py#L146

**Comment by wqx854987945** [comment]
Thank you for your reply. I understand that now!
