### ISSUE TITLE
Dataset Dowload Conflict: GCSv4 is no longer supported. 

### ISSUE THREAD

**Issue by cvolkc** [RIVeR-Lab/stereovoxelnet#9]
Hi , thanks for your work!

Following your [Link](https://app.globus.org/file-manager?origin_id=09b35740-377b-11ed-89ce-ede5bae4f491&origin_path=%2F) to download the respective dataset leads to Globus throwing the following error:

`Conflict: GCSv4 is no longer supported. Contact your sysadmin.`

Could it have to do with
[Support for Globus Connect Server version 4 ends on December 18, 2023](https://www.globus.org/blog/support-for-globus-connect-server-version-4-ends-on-december-18-2023)?

**Comment by lhy0807** [comment]
Thanks for bringing this up! Yes, it is indeed related to the Globus V4 issue. Northeastern hasn't updated it, so the service has been terminated (I guess temporarily). I'm working on transferring it to a more stable place and will get back to you when it is done.

**Comment by lhy0807** [comment]
Here's the new link on google drive. Hope it works :)
https://drive.google.com/drive/folders/1tQ1G0yUazbBiAxiOmdpvEUV3JSveTAF8?usp=sharing
